---
- name: yum install
  yum: name={{ item }} state=present
  with_items:
    - gcc
    - binutils
    - glibc
    - zlib
    - openssl
    - readline
    - ncurses
    - which
    #- pthread
    #
- name: put tar.gz
  unarchive:
    src: "http://jp.softether-download.com/files/softether/v4.22-9634-beta-2016.11.27-tree/Linux/SoftEther_VPN_Server/64bit_-_Intel_x64_or_AMD64/softether-vpnserver-v4.22-9634-beta-2016.11.27-linux-x64-64bit.tar.gz"
    dest: /usr/local/
    copy: no

- name: get pip
  get_url: 
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py

- name: install pip
  command: python /tmp/get-pip.py

- name:
  pip: name=pexpect

- name: make
  expect:
    command: "make"
    chdir: "/usr/local/vpnserver"
    responses:
      'Please choose one of above number:' : "1"


- name: 
  copy: >
    src=vpnserver.service
    dest=/etc/systemd/system

- name: 
  template: >
    src=setup.sh
    dest=/tmp
    mode=777

#- name: export PATH="/usr/local/vpnserver":$PATH
#- name: start vpnserver
  #service: name=vpnserver enabled=yes state=restarted
